spring:
  profiles:
    active: dev

# TODO: Configure the spring:datasource in the application-dev.yml file OR below
#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: <username>
#    password: <password>
#    url: jdbc:mysql://localhost:8889/im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8


  application:
    name: im-core

# logger configuration
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

appConfig:
  privateKey: 123456
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 50000
  imRoutingMethod: 3 # IM-sys routing Method: 1 random; 2 round-robin; 3 consistent hashing
  # If we choose consistent hashing as the routing algorithm, we need to determine which hash algorithm to use
  consistentHashingMethod: 1  # 1 TreeMap; 2 Custom Map
  callbackUrl: http://127.0.0.1:8989/callback
  modifyUserAfterCallback: false # Callback switch after user information changes
  addFriendAfterCallback: false # Callback switch after adding friends
  addFriendBeforeCallback: false # Callback switch before adding friends
  modifyFriendAfterCallback: false # Callback switch after modifying friends
  deleteFriendAfterCallback: false # Callback switch after deleting friends
  addFriendShipBlackAfterCallback: false # Callback switch after adding blacklist
  deleteFriendShipBlackAfterCallback: false # Callback switch after deleting the blacklist
  createGroupAfterCallback: false # Callback switch after creating group chat
  modifyGroupAfterCallback: false # Callback switch after modifying group chat
  deleteGroupAfterCallback: false # Callback switch after disbanding group chat
  deleteGroupMemberAfterCallback: false # Callback after deleting group members
  addGroupMemberAfterCallback: false # Callback after adding people to the group
  addGroupMemberBeforeCallback: false # Callback before adding people to the group


httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10
    password:

  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost
    username: guest
    password: guest
    #    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0

