spring:
  profiles:
    active: dev

# TODO: Configure the spring:datasource in the application-dev.yml file OR below
#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: <username>
#    password: <password>
#    url: jdbc:mysql://localhost:8889/im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8


  application:
    name: im-core

# logger configuration
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

appConfig:
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 50000
  imRoutingMethod: 3 # IM-sys routing Method: 1 random; 2 round-robin; 3 consistent hashing
  # If we choose consistent hashing as the routing algorithm, we need to determine which hash algorithm to use
  consistentHashingMethod: 1  # 1 TreeMap; 2 Custom Map
  callbackUrl: http://127.0.0.1:8000/callback

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectionTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


